-- Migration 20260817000006: Structured payout account banking fields
-- Affected: promoter_payout_accounts
-- Adds structured fields for bank name, account holder, account type,
-- masked last-4 display, routing identifiers, and branch info.
-- Full account number stored (column-level access via owner/admin RLS).
-- display_name retained for backward compat (now auto-generated by client).

alter table public.promoter_payout_accounts
  add column if not exists bank_name             text,
  add column if not exists account_holder_name   text,
  add column if not exists account_number_last4  text,          -- last 4 digits only
  add column if not exists account_number_full   text,          -- sensitive — owner/admin only
  add column if not exists account_type          text,          -- checking | savings | current | other
  add column if not exists branch_name           text,
  add column if not exists branch_code           text,
  add column if not exists routing_number        text,          -- ABA / routing for US ACH
  add column if not exists swift_bic             text;          -- SWIFT/BIC for wire

-- Grant authenticated users UPDATE on the new editable columns
-- (protected columns like status/verified_by remain admin-only per existing RLS)
grant update (
  bank_name,
  account_holder_name,
  account_number_last4,
  account_number_full,
  account_type,
  branch_name,
  branch_code,
  routing_number,
  swift_bic
) on public.promoter_payout_accounts to authenticated;

-- Notify PostgREST to reload schema cache so new columns are immediately usable
notify pgrst, 'reload schema';
